# Generated by Django 5.1.4 on 2025-02-25 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0002_reservation_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img_url',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.order')),
            ],
        ),
    ]
