# Generated by Django 5.1.7 on 2025-03-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
