# Generated by Django 5.1.7 on 2025-03-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0008_rename_space_preference_reservation_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.AddField(
            model_name='reservation',
            name='tables',
            field=models.ManyToManyField(to='webstore.table'),
        ),
    ]
