# Generated by Django 5.1.7 on 2025-03-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0009_table_remove_reservation_table_reservation_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('branch_location', models.CharField(choices=[('Bambalapitiya', 'Bambalapitiya'), ('Rajagiriya', 'Rajagiriya')], max_length=50)),
                ('feedback', models.TextField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
